sources = [
  "/home/yans/code/safelibs/ported/libuv/original/src/fs-poll.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/idna.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/random.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/threadpool.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/timer.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/async.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/core.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/fs.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/getaddrinfo.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/getnameinfo.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/linux.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/loop-watcher.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/loop.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/pipe.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/poll.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/process.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/random-devurandom.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/random-getrandom.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/random-sysctl-linux.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/signal.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/stream.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/tcp.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/tty.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/unix/udp.c",
  "/home/yans/code/safelibs/ported/libuv/original/src/uv-common.c"
]
